before

node.js:*
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
ReferenceError: foo is not defined
    at evalmachine.<anonymous>:*
    at Object.<anonymous> (*test*message*undefined_reference_in_new_context.js:*)
    at Module._compile (module.js:*)
    at Object..js (module.js:*)
    at Module.load (module.js:*)
    at Function._load (module.js:*)
    at Array.<anonymous> (module.js:*)
    at EventEmitter._tickCallback (node.js:*)
